MvcLibrary/Controllers/PanelController.cs
using MvcLibrary.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace MvcLibrary.Controllers
{
    public class PanelController : Controller
    {
        DBLibraryEntities db = new DBLibraryEntities();
        // GET: Panel
        [HttpGet]
        [Authorize]
        public ActionResult Index()
        {
            var membermail = Session["Mail"].ToString();
            var values = db.TBLMEMBERS.FirstOrDefault(m => m.Mail == membermail);
            ViewBag.fullname = values.Name + " " + values.LastName;
            return View(values);
        }
        [Authorize]
        [HttpPost]
        public ActionResult Index2(TBLMEMBERS p)
        {
            var member = (string)Session["Mail"];
            var infos = db.TBLMEMBERS.FirstOrDefault(m => m.Mail == member);
            infos.Password = p.Password;
            infos.Name = p.Name;
            infos.Mail = p.Mail;
            infos.LastName = p.LastName;
            infos.Photo = p.Photo;
            infos.Telephone = p.Telephone;
            infos.UserName = p.UserName;
            infos.School = p.School;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [Authorize]
        public ActionResult MyBooks()
        {
            var member = Session["Mail"].ToString();
            var values = db.TBLMEMBERS.FirstOrDefault(x => x.Mail == member);
            ViewBag.fullname = values.Name + " " + values.LastName;
            var infos = db.TBLMEMBERS.FirstOrDefault(m => m.Mail == member);
            var process = db.TBLPROCESS.Where(p => p.Member == infos.ID).ToList();
            return View(process);
        }
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login", "Login");
        }
    }
}

MvcLibrary/Views/Panel/Index.cshtml
@model MvcLibrary.Models.Entity.TBLMEMBERS
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutPanel.cshtml";
}
<h2>Library Member Informations</h2>
@using (Html.BeginForm("Index2", "Panel", FormMethod.Post))
{
    
<table class="table table-hover" style="margin-top:15px">
    @Html.HiddenFor(m => m.ID)
    <tr>
        <td>
            @Html.LabelFor(m => m.Mail)
            @Html.TextBoxFor(m => m.Mail, new { @class = "form-control" })
        </td>
    </tr>
    <tr>
        <td>
            @Html.LabelFor(m => m.Name)
            @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
        </td>
    </tr>
    <tr>
        <td>
            @Html.LabelFor(m => m.LastName)
            @Html.TextBoxFor(m => m.LastName, new { @class = "form-control" })
        </td>
    </tr>
    <tr>
        <td>
            @Html.LabelFor(m => m.UserName)
            @Html.TextBoxFor(m => m.UserName, new { @class = "form-control" })
        </td>
    </tr>
    <tr>
        <td>
            @Html.LabelFor(m => m.Password)
            @Html.TextBoxFor(m => m.Password, new { @class = "form-control" })
            <input type="button" value="Hide" id="showHideButton" class="btn btn-warning" name="showHideButton"/>
        </td>
    </tr>
    <tr>
        <td>
            @Html.LabelFor(m => m.Telephone)
            @Html.TextBoxFor(m => m.Telephone, new { @class = "form-control" })
        </td>
    </tr>
    <tr>
        <td>
            @Html.LabelFor(m => m.Photo)
            @Html.TextBoxFor(m => m.Photo, new { @class = "form-control" })
        </td>
    </tr>
    <tr>
        <td>
            @Html.LabelFor(m => m.School)
            @Html.TextBoxFor(m => m.School, new { @class = "form-control" })
        </td>
    </tr>
    <tr>
        <td><button class="btn btn-warning">Update Profile</button></td>
    </tr>
</table>
}
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script>
    $("#showHideButton").click(function () {
        if ($(this).val() == "Show") {
            $(this).val("Hide");
            $("#Password").attr("type", "text");
        } else {
            $(this).val("Show");
            $("#Password").attr("type", "password");
        }
    });
</script>

MvcLibrary/Views/Panel/MyBooks.cshtml
@using MvcLibrary.Models.Entity
@model List<TBLPROCESS>
@{
    ViewBag.Title = "MyBooks";
    Layout = "~/Views/Shared/_LayoutPanel.cshtml";
}

<h2>MyBooks</h2>
<br />
<table class="table table-striped table-bordered">
    <tr style="background-color:rgb(252,178,22)">
        <th>BookName</th>
        <th>LendDate</th>
        <th>ReturnDate</th>
        <th>Borrowback</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.TBLBOOK.Name</td>
            <td>@Convert.ToDateTime(item.DATEOFPURCHASE).ToString("dd/MM/yyyy")</td>
            <td>@Convert.ToDateTime(item.RETURNDATE).ToString("dd/MM/yyyy")</td>
            @if (Convert.ToDateTime(item.BorrowBack).ToString("dd/MM/yyyy") == "01.01.0001")
            {
                <td>The book is Still in the Member</td>
            }
            else
            {
                <td>@Convert.ToDateTime(item.BorrowBack).ToString("dd/MM/yyyy")</td>
            }
        </tr>
    }
</table>