MvcLibrary/Controllers/AnnouncementsController.cs
using MvcLibrary.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcLibrary.Controllers
{
    public class AnnouncementsController : Controller
    {
        DBLibraryEntities db = new DBLibraryEntities();
        // GET: Announcements
        public ActionResult Index()
        {
            var announcements = db.TBLAnnouncements.ToList();
            return View(announcements);
        }
        [HttpGet]
        public ActionResult AddNewAnnouncements()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddNewAnnouncements(TBLAnnouncements p)
        {
            db.TBLAnnouncements.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DeleteAnnouncements(int id)
        {
            var anno = db.TBLAnnouncements.Find(id);
            db.TBLAnnouncements.Remove(anno);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult ReturnAnnouncements(int id)
        {
            var anno = db.TBLAnnouncements.Find(id);
            return View("ReturnAnnouncements", anno);
        }
        public ActionResult AnnouncementsContents(int id)
        {
            var anno = db.TBLAnnouncements.Find(id);
            ViewBag.id = anno.ID;
            return View("AnnouncementsContents", anno);
        }
        public ActionResult UpdateAnnouncements(TBLAnnouncements p)
        {
            var anno = db.TBLAnnouncements.Find(p.ID);
            anno.Category = p.Category;
            anno.Content = p.Content;
            anno.Date = p.Date;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [Authorize]
        public ActionResult MemberAnnouncements()
        {
            var membermail = Session["Mail"].ToString();
            var values = db.TBLMEMBERS.FirstOrDefault(m => m.Mail == membermail);
            ViewBag.fullname = values.Name + " " + values.LastName;
            var annos = db.TBLAnnouncements.ToList();
            return View(annos);
        }
        [Authorize]
        public ActionResult MemberAnnouncementsContents(int id)
        {
            var membermail = Session["Mail"].ToString();
            var values = db.TBLMEMBERS.FirstOrDefault(m => m.Mail == membermail);
            ViewBag.fullname = values.Name + " " + values.LastName;
            var anno = db.TBLAnnouncements.Find(id);
            ViewBag.id = anno.ID;
            return View("MemberAnnouncementsContents", anno);
        }
    }
}

MvcLibrary/Views/Announcements/AddNewAnnouncements.cshtml
@model MvcLibrary.Models.Entity.TBLAnnouncements
@{
    ViewBag.Title = "AddNewAnnouncements";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>AddNewAnnouncements</h2>

<form class="form-group" method="post">
    <div></div>
    <div style="margin-top:15px">
        @Html.LabelFor(a => a.Category)
        @Html.TextBoxFor(a => a.Category, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        @Html.LabelFor(a => a.Content)
        @Html.TextAreaFor(a => a.Content, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        @Html.LabelFor(a => a.Date)
        <input type="text" name="Date" id="Date" class="form-control" value="@DateTime.Now.ToShortDateString()" />
    </div>
    <div style="margin-top:15px">
        <button class="btn btn-info" id="Btn1">Add New Announcements</button>
    </div>
</form>

MvcLibrary/Views/Announcements/AnnouncementsContents.cshtml
@model MvcLibrary.Models.Entity.TBLAnnouncements
@{
    ViewBag.Title = "Content";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>@ViewBag.id</h2>
@using(Html.BeginForm("AnnouncementsContents", "Announcements",FormMethod.Get))
{
    @Html.HiddenFor(a=>a.ID)
    <div></div>
    <div style="margin-bottom:15px" class="form-group">
        @Html.LabelFor(a => a.Category)
        @Html.TextBoxFor(a => a.Category, new { @class = "form-control", @readonly = "readonly" })
    </div>
    <div style="margin-bottom:15px" class="form-group">
        @Html.LabelFor(a=>a.Content)
        @Html.TextAreaFor(a=>a.Content, new { @class = "form-control", @readonly = "readonly" })
    </div>
    <div>
        <a href="/Announcements/Index/" class="btn btn-primary">Return Back</a>
    </div>
}

MvcLibrary/Views/Announcements/Index.cshtml
@using MvcLibrary.Models.Entity
@model List<TBLAnnouncements>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}
<h2>Announcements</h2>
<br />
<table class="table table-bordered">
    <tr>
        <th>AnnouncementsID</th>
        <th>AnnouncementsCategory</th>
        <th>AnnouncementsDate</th>
        <th>AnnouncementsContent</th>
        <th>Delete</th>
        <th>Update</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.ID</td>
            <td>@item.Category</td>
            <td>@Convert.ToDateTime(item.Date).ToString("dd/MM/yyyy")</td>
            <td><a href="/Announcements/AnnouncementsContents/@item.ID" class="btn btn-default" style="background-color:lightseagreen; color:white">Contents</a></td>
            <td><a href="/Announcements/DeleteAnnouncements/@item.ID" class="btn btn-danger">Delete</a></td>
            <td><a href="/Announcements/ReturnAnnouncements/@item.ID" class="btn btn-success">Update</a></td>
        </tr>
    }
</table>
<a href="/Announcements/AddNewAnnouncements/" class="btn btn-primary">New Announcements</a>

MvcLibrary/Views/Announcements/MemberAnnouncements.cshtml
@using MvcLibrary.Models.Entity
@model List<TBLAnnouncements>
@{
    ViewBag.Title = "MemberAnnouncements";
    Layout = "~/Views/Shared/_LayoutPanel.cshtml";
}

<h2>Announcements</h2>

<table class="table table-bordered table-striped">
    <tr>
        <th>ID</th>
        <th>Category</th>
        <th>Date</th>
        <th>Content</th>
    </tr>
    @foreach (var item in Model)
    {
<tr>
    <td>@item.ID</td>
    <td>@item.Category</td>
    <td>@Convert.ToDateTime(item.Date).ToString("dd/MM/yyyy")</td>
    <td><a href="/Announcements/MemberAnnouncementsContents/@item.ID" class="btn btn-default" style="background-color:lightseagreen; color:white">Contents</a></td>
</tr>
    }
</table>

MvcLibrary/Views/Announcements/MemberAnnouncementsContents.cshtml
@model MvcLibrary.Models.Entity.TBLAnnouncements
@{
    ViewBag.Title = "MemberAnnouncementsContents";
    Layout = "~/Views/Shared/_LayoutPanel.cshtml";
}

<h2>@ViewBag.id</h2>
@using (Html.BeginForm("AnnouncementsContents", "Announcements", FormMethod.Get))
{
    @Html.HiddenFor(a => a.ID)
    <div></div>
    <div style="margin-bottom:15px" class="form-group">
        @Html.LabelFor(a => a.Category)
        @Html.TextBoxFor(a => a.Category, new { @class = "form-control", @readonly = "readonly" })
    </div>
    <div style="margin-bottom:15px" class="form-group">
        @Html.LabelFor(a => a.Content)
        @Html.TextAreaFor(a => a.Content, new { @class = "form-control", @readonly = "readonly" })
    </div>
    <div>
        <a href="/Announcements/MemberAnnouncements/" class="btn btn-primary">Return Back</a>
    </div>
}

MvcLibrary/Views/Announcements/ReturnAnnouncements.cshtml
@model MvcLibrary.Models.Entity.TBLAnnouncements
@{
    ViewBag.Title = "ReturnAnnouncements";
    Layout = "~/Views/Shared/Layout.cshtml";
}

@using (Html.BeginForm("UpdateAnnouncements", "Announcements", FormMethod.Post))
{
    <div style="margin-bottom:15px"></div>
        <div style="margin-bottom:15px">
            @Html.HiddenFor(b => b.ID)
        </div>
        <div style="margin-bottom:15px">
            @Html.LabelFor(a=>a.Category)
            @Html.TextBoxFor(a=>a.Category, new { @class = "form-control" })
        </div>
        <div style="margin-bottom:15px">
            @Html.LabelFor(a=>a.Content)
            @Html.TextAreaFor(a=>a.Content, new { @class = "form-control" })
        </div>
        <div style="margin-bottom:15px">
            @Html.LabelFor(a=>a.Date)
            <input type="text" class="form-control" name="Date" value="@DateTime.Now.ToShortDateString()" />
        </div>
        <div>
            <button class="btn btn-warning">Update</button>
        </div>
}